version: '3.2'

services:
    app:
        image: "oven/bun:alpine"
        entrypoint: []
        command: "/bin/sh -c 'bun install && bun run --watch src/app.ts'"
        env_file:
            - .env
        ports:
        - "3000:3000"
        - "3001:3001"
        volumes: ["./:/home/bun/app"]
        network_mode: "host"

    # db:
    #     image: "postgres"
    #     ports:
    #         - "5432:5432"
    #     env_file:
    #         - .env
    #     depends_on:
    #         - app

    nginx:
        image: nginx:1.26.3
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
