# version: '3.2'

# services:
#     app:
#         image: "oven/bun:alpine"
#         entrypoint: []
#         command: "/bin/sh -c 'bun install && bun run src/server.ts'"
#         env_file:
#             - .env
#         ports:
#         - "3000:3000"
#         - "3001:3001"
#         volumes: ["./:/home/bun/app"]
#         networks:
#             - app-network

#     nginx:
#         image: nginx:1.26.3
#         ports:
#             - "80:80"
#         volumes:
#             - ./nginx.conf:/etc/nginx/conf.d/default.conf
#         depends_on:
#             - app
#         networks:
#             - app-network

# networks:
#     app-network:
#         driver: bridge
