version: '3.2'

services:
    app:
        image: "oven/bun"
        entrypoint: []
        command: "/bin/sh -c 'bun install && bun run --watch src/app.ts'"
        env_file:
            - .env
        ports:
        - "3000:3000"
        - "3001:3001"
        volumes: ["./:/home/bun/app"]
        network_mode: "host"

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
